trigger:
- azure-devops

variables:
  imageName: fitness-app
  acrLoginServer: fitnessacr123.azurecr.io
  tag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: Dockerfile
    containerRegistry: azure-chandan-acr
    tags: |
      $(tag)

# Update Helm values.yaml
- checkout: self
  persistCredentials: true

- script: |
    echo "Updating Helm values.yaml"

    sed -i "s/tag:.*/tag: \"$(tag)\"/" charts/fitness-app/values.yaml

    git config user.email "azure-devops@pipeline.com"
    git config user.name "azure-devops"

    git fetch origin
    git checkout -B azure-devops origin/azure-devops

    git add charts/fitness-app/values.yaml
    git commit -m "Update image tag to $(tag)"
    git push origin azure-devops
  displayName: Update Helm values
